import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "QIN — Quantitative Intelligence System", description: "CodePhantom's quantitative research architecture, experimental modules and evidence gates." };
const modules = [
  ["Existing research", "Rule-based strategies, historical data provenance, causal backtesting, chronological validation and strategy-level risk diagnostics exist in separate research tracks. Their evidence and limitations remain specific to each study."],
  ["Experimental foundations", "QIN is being developed as a common research layer. Versioned opportunity records, purged chronological labels and seeded Monte Carlo sequence stress are experimental foundations, subject to engineering and scientific review."],
  ["Machine-learning research", "Historical model comparisons exist, but robust improvement is not established. Setup ranking, calibration, XGBoost and regime analysis require suitable independent examples, reliable labels and baseline comparisons."],
  ["Adaptive intelligence roadmap", "Controlled retraining, drift monitoring, model comparison, rollback and promotion gates are planned. Observed trades and simulated counterfactual outcomes must remain distinct. Any future predictive integration begins in SHADOW mode."],
];
export default function QinPage() {
  return <div className="container-phantom pt-36 pb-24"><p className="font-mono text-cyber-blue">Quantitative technology</p><h1 className="mt-4 text-4xl text-ghost-white">QIN</h1><p className="mt-3 text-xl text-ghost-white">Quantitative Intelligence System</p><p className="mt-6 max-w-2xl text-muted-text">A research and decision-support framework for asking better questions about strategy behaviour, uncertainty and risk. Research output is reviewed before it can influence a product.</p><div className="mt-12 grid gap-6 md:grid-cols-2">{modules.map(([name, detail]) => <section key={name} className="rounded-2xl border border-metallic-silver/15 p-8"><h2 className="text-xl text-ghost-white">{name}</h2><p className="mt-4 text-muted-text">{detail}</p></section>)}</div><p className="mt-8 text-muted-text">No verified profitability, return or accuracy claim is made. Synthetic-index and Forex/CFD evidence are evaluated separately. Costs, overlapping observations and untouched holdouts are material research constraints. No live ML decisions or exploration are enabled.</p><Link className="mt-8 inline-block text-cyber-blue underline" href="/services">Discuss a quantitative software project</Link></div>;
}
