import type { Metadata } from "next";
import Link from "next/link";
import { Section } from "@/components/ui/section";
import { PageHero, Prose } from "@/components/page-hero";
import { company, contractingPartyName, legalEntityNotice } from "@/lib/company";

export const metadata: Metadata = {
  title: "Privacy",
  description: "How CodePhantom handles personal information on this website and in its products.",
  alternates: { canonical: "/privacy" },
};

const LAST_UPDATED = "2026-09-23";

export default function PrivacyPage() {
  return (
    <>
      <PageHero
        eyebrow="Privacy"
        title="Privacy notice"
        description={`Draft - last updated ${LAST_UPDATED}. It will be reviewed and finalised before any account-based product launches.`}
      />
      <Section className="border-t border-metallic-silver/10">
        <Prose>
          <h2>Who we are</h2>
          <p>{legalEntityNotice()}</p>
          <p>
            Questions or requests about your information: use the <Link href="/contact">Contact</Link> page. We aim to handle
            personal information in line with South Africa&apos;s Protection of Personal Information Act (POPIA).
          </p>

          <h2>This website</h2>
          <ul>
            <li>No analytics, advertising or tracking scripts are used, and the site sets no tracking cookies.</li>
            <li>
              Messages you type into Phantom Assistant are sent to this website&apos;s server only to generate an answer. The
              application does not store them.
            </li>
            <li>Like any website, our hosting provider may keep standard server logs (such as IP address and request time) for security and operations.</li>
          </ul>

          <h2>Accounts and apps (when launched)</h2>
          <p>To provide an account, {company.brand.name} will process:</p>
          <ul>
            <li>Account details: email address, username, optional display name. Passwords are handled by our authentication provider and stored only as secure hashes - we never see them.</li>
            <li>Licence and access records: your licence status, which market packs you are entitled to, and activation history.</li>
            <li>Device information: a random installation identifier generated by the app (stored only as a one-way hash), the device model, operating system and app version, and sign-in sessions. We do not collect IMEI numbers, serial numbers or advertising identifiers.</li>
            <li>Support tickets and the messages you send us, including how we verified your identity for a lost-phone request.</li>
            <li>Security and audit records of important account actions.</li>
            <li>Purchases, if and when products are sold: payment is handled by a payment provider; we do not receive your card number.</li>
          </ul>
          <p>Your app PIN stays on your device and is never sent to us.</p>

          <h2>Why we use it</h2>
          <p>To run your account and licence, keep it secure (including preventing account sharing), provide support, meet legal obligations, and improve our products. We do not sell personal information.</p>

          <h2>Who processes it for us</h2>
          <ul>
            <li>Supabase (database and authentication), our hosting provider, and an email provider for account emails.</li>
            <li>A payment provider, only once paid products exist.</li>
            <li>If you join the CodePhantom Traders WhatsApp group, WhatsApp/Meta processes your participation under its own terms; group members can see your number.</li>
          </ul>

          <h2>How long we keep it</h2>
          <p>Only as long as needed for the purposes above and any legal requirements. Detailed retention periods will be published before launch.</p>

          <h2>Your rights</h2>
          <p>You may ask for access to, correction of, export of or deletion of your personal information, and you may object to processing or lodge a complaint with South Africa&apos;s Information Regulator. Contact us to make a request.</p>

          <h2>Children</h2>
          <p>Our products are not intended for anyone under 18.</p>

          <h2>Changes</h2>
          <p>We will update this page and its date when this notice changes. Controller: {contractingPartyName()}.</p>
        </Prose>
      </Section>
    </>
  );
}
